export const GET_SHEET_ROWS_AND_COLS = 'SPREADSHEET_GET_SHEET_ROWS_AND_COLS';
export const GET_SHEET_ROWS_AND_COLS_SUCCESS = 'GET_SHEET_ROWS_AND_COLS_SUCCESS';
export const GET_SHEET_ROWS_AND_COLS_FAILURE = 'GET_SHEET_ROWS_AND_COLS_FAILURE';

export const CREATE_SHEET = 'SPREADSHEET_CREATE_SHEET';
export const CREATE_SHEET_SUCCESS = 'SPREADSHEET_CREATE_SHEET_SUCCESS';

export const UPDATE_CELL = 'SPREADSHEET__UPDATE_CELL';
export const UPDATE_CELL_SUCCESS = 'SPREADSHEET_UPDATE_CELL_SUCCESS';

export const CREATE_COLUMN = 'SPREADSHEET_CREATE_COLUMN';
export const CREATE_COLUMN_SUCCESS = 'SPREADSHEET_CREATE_COLUMN_SUCCESS';

export const CREATE_ROW = 'SPREADSHEET_CREATE_ROW';
export const CREATE_ROW_SUCCESS = 'SPREADSHEET_CREATE_ROW_SUCCESS';
