export const GET_SHEET = 'SPREADSHEET_GET_SHEET';
export const GET_SHEET_SUCCESS = 'SPREADSHEET_GET_SHEET_SUCCESS';
export const GET_SHEET_FAILURE = 'SPREADSHEET_GET_SHEET_FAILURE';

export const CREATE_SHEET = 'SPREADSHEET_CREATE_SHEET';
export const CREATE_SHEET_SUCCESS = 'SPREADSHEET_CREATE_SHEET_SUCCESS';

export const UPDATE_CELL = 'SPREADSHEET__UPDATE_CELL';
export const UPDATE_CELL_SUCCESS = 'SPREADSHEET_UPDATE_CELL_SUCCESS';
